CREATE TABLE [Categories] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [CreatedAt] DATETIME2 NOT NULL,
    [CreatedBy] UNIQUEIDENTIFIER NOT NULL,
    [IsDeleted] BIT NOT NULL CONSTRAINT [DF_Categories_IsDeleted] DEFAULT(0),
    [Name] NVARCHAR(100) NOT NULL
);
